#!/bin/sh
# Regenerates src/mono-font.ts from JetBrains Mono (OFL-1.1) release TTFs.
set -e
cd "$(dirname "$0")/.."
for f in Regular Bold Italic; do
  curl -sL -o "scripts/JetBrainsMono-$f.ttf" \
    "https://github.com/JetBrains/JetBrainsMono/raw/master/fonts/ttf/JetBrainsMono-$f.ttf"
done
node -e '
const fs = require("fs");
const cuts = ["Regular", "Bold", "Italic"];
let out = "// Generated by scripts/gen-mono-font.sh — JetBrains Mono (OFL-1.1), do not edit.\nexport const monoFontFiles: Record<string, string> = {\n";
for (const c of cuts) {
  const b64 = fs.readFileSync("scripts/JetBrainsMono-" + c + ".ttf").toString("base64");
  out += "  \x27JetBrainsMono-" + c + ".ttf\x27: \x27" + b64 + "\x27,\n";
}
out += "};\n";
fs.writeFileSync("src/mono-font.ts", out);
'
rm -f scripts/JetBrainsMono-*.ttf
echo "src/mono-font.ts regenerated"
